// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMuMlyYV1d4Hg6VFfR63c0pl_JUa1GsGo',
    appId: '1:1035548008604:web:ce35ae9cdd7baebc320d59',
    messagingSenderId: '1035548008604',
    projectId: 'mesclainvest-b2967',
    authDomain: 'mesclainvest-b2967.firebaseapp.com',
    storageBucket: 'mesclainvest-b2967.firebasestorage.app',
    measurementId: 'G-Z1XV22Z6L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU1e0VukbUBAt60Kt75RZ6ecXHw4bK8Pc',
    appId: '1:1035548008604:android:466d00de4e14cb9b320d59',
    messagingSenderId: '1035548008604',
    projectId: 'mesclainvest-b2967',
    storageBucket: 'mesclainvest-b2967.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9JdzkxU1kIrqU4mRY_3K8IUeo2iT-rM',
    appId: '1:1035548008604:ios:a79255b1c0847d13320d59',
    messagingSenderId: '1035548008604',
    projectId: 'mesclainvest-b2967',
    storageBucket: 'mesclainvest-b2967.firebasestorage.app',
    iosBundleId: 'com.example.mesclaInvestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb9JdzkxU1kIrqU4mRY_3K8IUeo2iT-rM',
    appId: '1:1035548008604:ios:a79255b1c0847d13320d59',
    messagingSenderId: '1035548008604',
    projectId: 'mesclainvest-b2967',
    storageBucket: 'mesclainvest-b2967.firebasestorage.app',
    iosBundleId: 'com.example.mesclaInvestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMuMlyYV1d4Hg6VFfR63c0pl_JUa1GsGo',
    appId: '1:1035548008604:web:22c5c5f2be7754fc320d59',
    messagingSenderId: '1035548008604',
    projectId: 'mesclainvest-b2967',
    authDomain: 'mesclainvest-b2967.firebaseapp.com',
    storageBucket: 'mesclainvest-b2967.firebasestorage.app',
    measurementId: 'G-F2WWXFKWQB',
  );
}
